# Generated by Django 2.2.6 on 2019-11-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('image', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('price_s', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('image', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('image', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('image', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('price_s', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('toppings_limit', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('image', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('price_s', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('toppings_limit', models.IntegerField(blank=True)),
                ('topping', models.ManyToManyField(blank=True, related_name='ToppingSub', to='orders.SubTopping')),
            ],
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('image', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('price_s', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('toppings_limit', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
