# Generated by Django 2.0.3 on 2019-11-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191104_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinnerplatter',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='pasta',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='salad',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='sicilianpizza',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='sub',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='subtopping',
            name='price_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subtopping',
            name='price_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterIndexTogether(
            name='dinnerplatter',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='pasta',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='salad',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='sicilianpizza',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='sub',
            index_together={('id', 'slug')},
        ),
    ]
