# Generated by Django 2.0.3 on 2019-11-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191105_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='toppings_limit',
        ),
    ]
