# Generated by Django 2.0.3 on 2019-11-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_sub_toppings_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopping',
            name='price_l',
        ),
        migrations.RemoveField(
            model_name='subtopping',
            name='price_s',
        ),
    ]
