# Generated by Django 2.0.3 on 2019-11-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191105_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopping',
            name='price_l',
        ),
        migrations.RemoveField(
            model_name='subtopping',
            name='price_s',
        ),
    ]
