# Generated by Django 2.0.3 on 2019-11-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191105_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='topping',
        ),
    ]
